### ISSUE TITLE
ar9271 and ar7010 need to be unplugged and plugged back in to function after boot

### ISSUE THREAD

**Issue by SolidHal** [SolidHal/PrawnOS#103]
If a ar9271 or ar7010 usb dongle are plugged in before the computer is turned on, they will not be functional.

This happens because on boot, but before the filesystem is mounted, the usb device asks the kernel for the firmware, but since the firmware is on the filesystem and is not yet mounted the kernel cannot provide it. 

The firmware may be able to be included in the kernel, which would fix this issue. 

### Workaround:
Leave the usb wifi device unplugged, and plug it in after the system boots. 

This workaround doesnt work for devices with the ar9271 soldered in to replace the webcam, so for now, this script works for me: 
```
#/bin/bash

#Resets the usb
#Since the firmeare is on the mmc, but the ath9k module is built in to the kern$
#On boot, the kernel doesn't wait for the filesystem to become available before
#Trying to give the ath9k device a firmware, causing the kernel to not find
#The firmware. 

#Fix this by trying to build the firmware into the kernel

echo 0 > /sys/bus/usb/devices/3-1/authorized
echo 1 > /sys/bus/usb/devices/3-1/authorized

```
Worst case scenario, I'll wrap this into a patch, likely as a boot script.

**Comment by tehbra1n** [comment]
I had wondered why this happened with the ar9271 but didn't care enough to dig into it.  As you mentioned, reseating the dongle after boot does the trick.  A boot script to automate the reset is a pretty simple thing for the user to do if desired too.
