### ISSUE TITLE
consider nls_iso_8859-1 for pmount

### ISSUE THREAD

**Issue by tslilc** [SolidHal/PrawnOS#107]
The popular removable storage mounting tool `pmount` needs in-kernel support for certain unicode character-sets in order to correctly interact with FAT partitions. I have tested and `CONFIG_NLS_ISO_8859_1=y` seems to be the culprit. I hope this will make it into PrawnOS :)

**Comment by SolidHal** [comment]
Thanks for the report and for doing the testing! Should be functional now.
