### ISSUE TITLE
InstallToInternal.sh: confirmation hints wrongly about its default choice

### ISSUE THREAD

**Issue by jonassmedegaard** [SolidHal/PrawnOS#113]
`scripts/InstallScripts/InstallToInternal.sh` initially asks this:
> This will ERASE ALL DATA ON THE INTERNAL STORAGE (EMMC) and reboot when finished, do you want to continue? [Y/n]

Confusingly if hitting enter, the script does not continue but instead bails out.

Please flip the trailing hints to be "[y/N]" instead, to capitalize what is in fact the default choice.

**Comment by SolidHal** [comment]
Good catch, pushing a fix. Thanks!
