### ISSUE TITLE
omits recommended packages

### ISSUE THREAD

**Issue by jonassmedegaard** [SolidHal/PrawnOS#115]
Default xfce install omits a few recommended packages:
* bash-completion
* e2fsprogs-l10n
* laptop-detect
* libatm1
* libgpg-error-l10n
* libnss-systemd
* libpam-cap
* light-locker
* murrine-themes
* nftables
* uuid-runtime

Among those, only a few are undisputably sensible:
* light-locker
* murrine-themes

Light-locker is known to cause problems so appreciated being dealt with in custom ways for PrawnOS, and murrine-themes clashes with numix-gtk-theme.

Some are harmless but also tiny, and I suggest including just to simplify to only have recommendations excluded for strong reasons:
* e2fsprogs-l10n
* laptop-detect
* libatm1
* libgpg-error-l10n
* uuid-runtime

Some are outright useful, and if not others then at least ensure these get installed:
* bash-completion
* libnss-systemd
* libpam-cap
* nftables

**Comment by SolidHal** [comment]
Looked over the list and seems pretty reasonable, I'll add them and give it a test.
