### ISSUE TITLE
ExpandExternalInstall must be adjusted for new partition layout

### ISSUE THREAD

**Issue by l-jonas** [SolidHal/PrawnOS#122]
<https://github.com/SolidHal/PrawnOS/blob/master/scripts/InstallScripts/ExpandExternalInstall.sh> does not work anymore.

With the introduction of encryption support, a new partition was added. I could get the script working by replacing every reference to partition 2 by a reference to partition 3.

**Comment by SolidHal** [comment]
I'll have to rework ExpandExternalInstall.sh in general to support encryption, this will have to be part of it.

**Comment by SolidHal** [comment]
Once #128 gets merges, the script has a better chance of working without major changes

**Comment by SolidHal** [comment]
This is fixed in master with the new InstallPrawnOS.sh
