### ISSUE TITLE
/dev/mappper instead of /dev/mapper in InstallToInternal.sh copy to fstab

### ISSUE THREAD

**Issue by rk-zero** [SolidHal/PrawnOS#124]
https://github.com/SolidHal/PrawnOS/blob/c80f515d9a269fb7b04b115fb1643c420a6b7bee/scripts/InstallScripts/InstallToInternal.sh#L118

During rework i found this spelling error, may be the reason why lxde has problems with file manager.

**Comment by SolidHal** [comment]
Thanks!
