### ISSUE TITLE
You cannot say no to encryption due to missing No ) Statement

### ISSUE THREAD

**Issue by rk-zero** [SolidHal/PrawnOS#125]
https://github.com/SolidHal/PrawnOS/blob/c80f515d9a269fb7b04b115fb1643c420a6b7bee/scripts/InstallScripts/InstallToInternal.sh#L89-L103

fixed it with:

        case $yn in
        Yes ) ....
        No )
        	break
        	;;
        * )
            echo "Invalid Option, please enter Yes or No, 1 or 2"
            ;;

which works for every case, invalid input, 1 and 2.

**Comment by SolidHal** [comment]
Good catch, I tested lots of user input for enabling encryption but none for not! 
The reason for the odd 
```
case $yn,$REPLY in 
Yes,*|*,Yes ) 
```
syntax instead of just 
```
case $yn in 
Yes ) 
```

Is to enable accepting 1 or Yes and 2 or No, otherwise you can only input 1 and 2 which I didn't think was very user friendly.
