### ISSUE TITLE
Screen blinks white on transistion from libreboot to kernel, otherwise boots fine

### ISSUE THREAD

**Issue by SolidHal** [SolidHal/PrawnOS#13]
Try kernel cmdline options:
nosplash
spalsh
vga=### ex vga=791
quiet
noquiet, 
console=ttyS2,115200n8 
earlyprintk=ttyS2,115200n8 
console=tty1

**Comment by melye** [comment]
Tried every option, still blinks on boot. C201 with 2GB RAM.

**Comment by SolidHal** [comment]
closing as not really a problem
