### ISSUE TITLE
v0.17-alpha UI issues

### ISSUE THREAD

**Issue by tehbra1n** [SolidHal/PrawnOS#131]
On a completely fresh install with root encryption, after logging in the UI is missing icons on the ribbon and lacks a background.

I noticed similar behavior on recent versions when doing a full apt update/upgrade, so perhaps some recent package update is causing the issue.

![IMG_20191018_091416](https://user-images.githubusercontent.com/17303996/67098324-fa14ee00-f189-11e9-8f77-b09793e3d1c4.jpg)

**Comment by SolidHal** [comment]
Thanks @tehbra1n !
