### ISSUE TITLE
README inconsistent about build OS requirements

### ISSUE THREAD

**Issue by JeremyRand** [SolidHal/PrawnOS#136]
The README states:

> Building PrawnOS has been tested on Debian 10 Buster (in a VM)
> _stretch doesn't work as the version of gcc-arm-none-eabi is too old_
> This is the only build enviroment that is supported.

However, it also states:

> This has only been tested on a Debian stretch VM, and borrows some components from the host system to setup apt/debootstrap during the build process so I would recommend using a Debian Stretch VM to avoid any issues. 

I'm guessing that the latter paragraph should be updated to mention Buster instead of Stretch.

**Comment by SolidHal** [comment]
You would be correct in that assumption, I have fixed it. Thanks!
