### ISSUE TITLE
Dmesg doesn't silence during decrypting

### ISSUE THREAD

**Issue by SolidHal** [SolidHal/PrawnOS#146]
dmesg -D before decrypt isn't working. Try `dmesg -n 1`?

**Comment by SolidHal** [comment]
#147 includes a commit that fixes this

**Comment by rk-zero** [comment]
i think dmesg -n 1 is too hard (only kernel panics). with -n 2 it at least acks if you put a new usb device in f. e.

But it works, so you can just use -n.

https://linuxconfig.org/introduction-to-the-linux-kernel-log-levels

Please consult /proc/sys/kernel/printk for the normal log level used. i set it to 7, but it seems normal is 4, so i don't know.
