### ISSUE TITLE
Commits failing CI due to github CI networking errors

### ISSUE THREAD

**Issue by SolidHal** [SolidHal/PrawnOS#185]
I have seen several commits fail testing. These failure to fetch due to "undertermined error"s
```
E: Failed to fetch http://ftp.us.debian.org/debian/pool/main/g/gtk+3.0/libgtk-3-common_3.24.5-1_all.deb  Undetermined Error [IP: 208.80.154.15 80]
```
We should probably bake some error handling for this into the CI script

**Comment by austin987** [comment]
Which build was this?

**Comment by SolidHal** [comment]
Unfortunately it looks like the builds get removed when re-ran, which is annoying :/ 
So I can't link to the failures.

**Comment by SolidHal** [comment]
Seems this issue has been mostly resolved by the retry login in the apt scripts, closing
