### ISSUE TITLE
Move PrawnOS deb repo to sources.list.d

### ISSUE THREAD

**Issue by JeremyRand** [SolidHal/PrawnOS#186]
Would a PR be accepted that moves the `https://deb.prawnos.com` repo from `sources.list` to `sources.list.d/prawnos.list`?  This would make it easier for PrawnOS to interoperate with software that needs to modify `sources.list` such as Kicksecure.

**Comment by rk-zero** [comment]
+1 on this, way cleaner solution.

**Comment by SolidHal** [comment]
Yeah, that would be accepted.

**Comment by JeremyRand** [comment]
Okay cool, I'll work on a PR for it shortly.
