### ISSUE TITLE
PrawnOS 1.1 armhf on C201P + Gnome desktop results in crash on boot

### ISSUE THREAD

**Issue by tehbra1n** [SolidHal/PrawnOS#231]
Both using the armhf image and building from source results in a crash on boot with Gnome but not Xfce.  It seems like the boot process gets as far as starting the Gnome desktop manager, then an endless stream of error messages scrolls until the power button is held down to power of the laptop.

I'm not sure if there is an easy way to get a text copy of the output but here is a pic.  
![PXL_20201031_150928944](https://user-images.githubusercontent.com/17303996/97782871-6a5e9980-1b6a-11eb-8daf-7db6d5324d47.jpg)

**Comment by gregordinary** [comment]
I experienced the same thing, however I was testing 4k patches on the latest 1.1 release so I didn't know if it was the patches or not. But I can confirm this happened only in gnome and not xfce

**Comment by SolidHal** [comment]
Looking into it, thanks for the report

**Comment by SolidHal** [comment]
kernel 5.9.4 seems to have fixed the issue, I'll make a 1.11 release soon with this fix

**Comment by SolidHal** [comment]
released 1.2 which fixes this, closing.
