### ISSUE TITLE
lilyterm fails to run, broken config

### ISSUE THREAD

**Issue by austin987** [SolidHal/PrawnOS#256]
Noticed we have 'lilyterm' (https://lilyterm.luna.com.tw/) installed, saw it before Xfce4 terminal when trying to test something on a fresh install. That failed with a GUI error, saying that ~/.config/lilyterm/default.conf is in the old format and needs to be updated.

Which is strange, because ~/.config/lilyterm doesn't exist..

Anyway, it's a lilyterm bug that it gives that error if the file doesn't exist, but to the end user, it's arguably a bug in PrawnOS. We could ship a config file, or remove it.

I'd vote for removing it (particularly since we already ship xfce-terminal/gnome-terminal, which work out of the box), though I'm not sure how it's installed. I'm guessing as a suggestion/dependency of something, since `git grep lilyterm` shows no results.

**Comment by SolidHal** [comment]
I agree, it must be tagging along as a rec from some package.

**Comment by austin987** [comment]
Thanks for the fix, but that only removes it from gnome, but not xfce (which also has it installed, that's how I noticed it ;) ).

**Comment by SolidHal** [comment]
ah, good point. I only first noticed it in gnome so I assumed it was a gnome-specific issue.
