### ISSUE TITLE
Consider enabling CONFIG_EXFAT_FS in the kernel

### ISSUE THREAD

**Issue by gregordinary** [SolidHal/PrawnOS#259]
I occasionally use exFAT to format higher capacity drives that need compatibility with macOS and/or Windows, in addition to GNU/Linux. 

Kernel 5.4 introduced an exFAT kernel driver, and vastly improved it in 5.7. It can be enabled with CONFIG_EXFAT_FS and offers some performance gains over the FUSE implementation. 

Not a must have, but convenient.

**Comment by SolidHal** [comment]
funny enough, I thought I had already enabled this. Turns out it was only on arm64. Now enabled on armhf as well. Thanks @gregordinary :)
