### ISSUE TITLE
please only track *source* in git

### ISSUE THREAD

**Issue by jonassmedegaard** [SolidHal/PrawnOS#272]
700 MB PNG files in filesystem/resources/logo/icons/OtherColors? Really?
Please use SVG as source and keep *only* source in git - Inkscape is a wonderful tool for that.

180 MB tarballs in filesystem/packages? Really?
Please instead track each of those (only!) as a separate git, imported with `gbp --import-orig --pristine-tar` part of the `git-buildpackage` package.

**Comment by SolidHal** [comment]
While this would definitely be nice, I doubt I'll get around to changing this anytime soon so I'm closing for now.
