### ISSUE TITLE
Cannot install to emmc to c201

### ISSUE THREAD

**Issue by gregordinary** [SolidHal/PrawnOS#280]
Latest build from git, choosing the option to install to the emmc on the c201 results in the following error: 
```
/dev//dev/mmcblk1 does not exist, have you plugged in your target sd card or usb device? 
```
![IMG_20210114_161037](https://user-images.githubusercontent.com/33880035/104653841-3551e580-5689-11eb-80de-98adcb21b44a.jpg)

A bit out of my comfort zone, but I believe the code from [get_emmc_devname](https://github.com/SolidHal/PrawnOS/blob/c905b0178cd6eff2e888b8a8cc80a453865d7714/scripts/InstallScripts/InstallPrawnOS.sh#L39-L46):
```
get_emmc_devname() {
    local devname=$(ls /dev/mmcblk* | grep -F boot0 | sed "s/boot0//")
    if [ -z "$devname" ]
    then
        echo "Unknown device! can't determine emmc devname. Please file an issue with the output of fdisk -l if you get this on a supported device"; exit 1;;
    fi
    echo $devname
}
```

is returning the value as "/dev/mmcblk1" which is being referenced on [line 101](https://github.com/SolidHal/PrawnOS/blob/c905b0178cd6eff2e888b8a8cc80a453865d7714/scripts/InstallScripts/InstallPrawnOS.sh#L101) of InstallPrawnOS.sh:
```
            [Ii]* ) TARGET=/dev/$(get_emmc_devname)p; TARGET_EMMC=true; break;;
```
resulting in the additional /dev/

**Comment by austin987** [comment]
Try https://github.com/SolidHal/PrawnOS/pull/268/commits/bf639d77685751b82c469b78c2a378866a479a8e

**Comment by gregordinary** [comment]
Thanks!
