### ISSUE TITLE
Possible to build PrawnOS into a ChromeOS recovery image?

### ISSUE THREAD

**Issue by spiralw** [SolidHal/PrawnOS#284]
Hi, I have a Librebooted C201P and I broke my PrawnOS install while having USB boot disabled. Google's official ChromeOS recovery images don't work (something about needing to run `cgpt repair` because the GPT headers are invalid, [screenshot](https://user-images.githubusercontent.com/64013111/116191938-0ab20700-a725-11eb-8cb5-fa1e439dde87.jpg)). 
As far as I understand, recovery images are validated by checking the kernel signature. Is there any way to use the official recovery kernel to boot into the PrawnOS installer, or whatever Linux shell?
My chromebook is currently bricked, so any help would be very much appreciated.

**Comment by tehbra1n** [comment]
This might not be exactly what you're looking for, but I always have a ton
of trouble doing ChromeOS recovery on any Chromebook.  I believe that the
process can be very finicky about the SD card/USB thumb drive used.  I end
up having to grab a ton of different media and trying it repeatedly using
different machines to write the recovery media and different SD cards/USB
drives until the recovery actually works on the bricked Chromebook.
