### ISSUE TITLE
Supported devices

### ISSUE THREAD

**Issue by wehkah** [SolidHal/PrawnOS#302]
Hello!

The list of supported devices is very... clearly arranged. There are just 5 devices listed. 

Is there any chance that PrawnOS will (ever) run on a Lenovo Duet? I am not specialized in hardware, but as much as I know, this device has an ARM64 CPU, so to my simple mind, this means it doesn't differ much from the two ARM64 models listed. 

On the other hand: naively, I downloaded the ARM64 image and tried to boot it on the Duet. This resulted in a blank screen without anything happening, even after 15 minutes.

**Comment by SolidHal** [comment]
@wehkah likely not, unless someone with the device works to add support. I don't have the hardware. The black box security chip added to the machine severely reduces my interest in it.
