### ISSUE TITLE
Map function keys to function

### ISSUE THREAD

**Issue by SolidHal** [SolidHal/PrawnOS#33]
The top keys: Brightness controls and volume controls
Should be mapped accordingly. 
Since there is no function key on the keyboard, maybe map the "search" key to it? 
Otherwise use alt or ctl?

**Comment by SolidHal** [comment]
So, the backlight is supported by backlight-pwm in the kernel but there doesn't seem to be a userspace driver. Soooo we have to hack one:

Need to change permissions of the brightness objects

```
/etc/udev/rules.d/backlight.rules

ACTION=="add", SUBSYSTEM=="backlight", KERNEL=="backlight", RUN+="/bin/chgrp video /sys/class/backlight/%k/brightness"
ACTION=="add", SUBSYSTEM=="backlight", KERNEL=="backlight", RUN+="/bin/chmod g+w /sys/class/backlight/%k/brightness"

```

Then add user to 'video' group in the install scripts

Add these to /usr/sbin/

bl_up.sh
```
#!/bin/bash
DEV=/sys/class/backlight/backlight
BL=$(cat $SYSDEV/brightness)
MAX=$(cat $SYSDEV/max_brightness)

if [ $BL -lt 5 ]; then
	BL=$((BL + 1))
else
	BL=$((BL + ( BL / 4 )))
fi
if [ $BL -gt $MAX ]; then
	BL=$MAX
fi
echo $BL > $DEV/brightness
```

bl_down.sh
```
#!/bin/bash
DEV=/sys/class/backlight/backlight
BL=$(cat $DEV/brightness)
if [ $BL -eq 0 ]; then
	exit 0
fi
if [ $BL -lt 5 ]; then
	BL=$((BL - 1))
else
	BL=$((BL - ( BL / 4 )))
fi
echo $BL > $DEV/brightness
```

Then add keybindings....

**Comment by SolidHal** [comment]
This was implemented some time ago. Closing.

**Comment by troublew** [comment]
Hie, I've just installed prawnOs on my c201 (nice work btw).
But the function keys to not work at all (return "~").
Is there something I'm doing wrong? (I've rightly installed the ./InstallPackage.sh script).
Thanks you.

**Comment by SolidHal** [comment]
@troublew thanks! The function keys all seem to work properly in xfce on my 3 machines, do you happen to be using lxqt?

**Comment by troublew** [comment]
Yes, I use lxqt.
