### ISSUE TITLE
Bluetooth support

### ISSUE THREAD

**Issue by dimkr** [SolidHal/PrawnOS#40]
CSR8150 Bluetooth dongles (which cost around $1-2 on eBay and Aliexpress) work with Linux-libre! `CONFIG_BT_HCIBTUSB` and `CONFIG_BT_INTEL` result in `btusb.ko` and `btintel.ko`, which support this chip bloblessly.

I had this dongle for about a year and only today I had the time and motivation to get my Bluetooth speakers to work with the C201.

To test the dongle: run `bluetoothctl` (`scan`, `devices, ``pair` and `connect`), install `pulseaudio` with `pulseaudio-module-bluetooth` enabled and make the Bluetooth sink the default using `pactl`. Then, everything including `speaker-test` will play sound through the speakers.

**Comment by dimkr** [comment]
For reference: https://github.com/dimkr/devsus/commit/0e31c14212ffe8cb809bfb67822e7d8f3bcce420

**Comment by SolidHal** [comment]
Awesome. I'm sure theres some decent interest in bluetooth functionality. I'll enable those when I get home later!

**Comment by SolidHal** [comment]
@dimkr I've enabled the required kernel config options. Would you mind giving it a test? I don't own the required dongle.

**Comment by dimkr** [comment]
> Would you mind giving it a test?

Sure, let me know when there's a prebuilt image with these changes.

**Comment by SolidHal** [comment]
@dimkr Theres a prebuilt image under "releases" with the change. Thank for testing it!

**Comment by dimkr** [comment]
The dongle has been detected correctly in `dmesg`.

**Comment by duvh93** [comment]
Hello! Is it CSR8150 or CSR8510? I barely manage to find the former dongles for sale on the internet

**Comment by SolidHal** [comment]
@duvh93 The CSR8150 is what dimkr had tested with, so I don't know if the CSR8510 would work. Can't seem to find a definitive answer whether the linux kernel bluetooth drivers support it. You may have more luck if you search for a specific brand/model of bluetooth device in this case. 

If you end up picking one up and it doesn't work, let me know.

**Comment by dimkr** [comment]
@duvh93 Probably a typo

**Comment by SolidHal** [comment]
Looks like it is a typo, fixed in the README. thanks @duvh93 and @dimkr

**Comment by rk-zero** [comment]
Bluetooth support is great in 1.0.0 - even my quirky ms mouse now works out of the box with correct update intervals.

**Comment by SolidHal** [comment]
@rk-zero thats great to hear!
