### ISSUE TITLE
Chromium and Firefox crash

### ISSUE THREAD

**Issue by bkeys** [SolidHal/PrawnOS#64]
If you install either browser on a fresh install and try to run them, they will both crash

**Comment by albsod** [comment]
This is what I did after a fresh install to deal with Firefox while getting OS security updates:
- sudo apt remove firefox-esr
- enabled the stretch security repository in /etc/apt/sources.list
- sudo apt update && sudo apt-get upgrade
- changed 'stretch' to 'buster' everywhere in /etc/apt/sources.list
- sudo apt update
- sudo apt-get install firefox-esr (i.e. from buster, and accepted installing the dependencies)
- changed 'buster' to 'stretch' in /etc/apt/sources.list again
- sudo apt update

This way my system is mostly Debian Stretch with security updates but with a working new Firefox version from Buster. Upgrading the whole system to buster didn't work for me; it broke the XFCE desktop environment.

**Comment by ericfont** [comment]
Thanks...these instructions worked for me.  I was hoping to also install chromium but noticed debian buster only has i386 and amd64 builds, no arm builds, for some reason.

**Comment by SolidHal** [comment]
This is now resolved in the most recent release. Closing. Comment if youd like it reopened.
