### ISSUE TITLE
Installer doesn't set a root password

### ISSUE THREAD

**Issue by JeremyRand** [SolidHal/PrawnOS#66]
The installer doesn't set a password on the `root` user, it only sets a password on the non-root user that's created.  I assume this is an oversight, since allowing logging in as root without a password is a pretty big issue.  (I only explicitly tested this on Buster, but I don't recall getting asked for a root password when installing PrawnOS with Stretch either.)

**Comment by SolidHal** [comment]
resolved by 633314928242979de3c6f315eefc86aef134b91f
