### ISSUE TITLE
linux-libre 4.17.2 source code is no longer available

### ISSUE THREAD

**Issue by Whelle** [SolidHal/PrawnOS#67]
Archive with linux-libre 4.17.2 source was deleted from linux-libre.fsfla.org . We should change kernel version or manually deblob original kernel.

**Comment by SolidHal** [comment]
Well, thats a bummer. I guess I'll look into using a LTS kernel. Probably should anyway.

**Comment by SolidHal** [comment]
So, sound doesn't work properly in 4.19.13. Spent a little time trying to fix it but didnt get it working. Trying 4.17.19 which was the last 4.17 release and will "always" be available from linux-libre

**Comment by SolidHal** [comment]
4.17.19 seems to have everything working, so this issue is now resolved  by commit 2b98b312ecc132e44afced37130fed99c4054877
