### ISSUE TITLE
Is fsck being ran on boot after improper shutdowns?

### ISSUE THREAD

**Issue by Anthony-Sensors** [SolidHal/PrawnOS#82]
When I dmesg I get the following EXT4-fs error:

[    3.203707] EXT4-fs error (device mmcblk2p2): ext4_mb_generate_buddy:745: group 1441, block bitmap and bg descriptor inconsistent: 7962 vs 7963 free clusters
[    4.137750] EXT4-fs error (device mmcblk2p2): ext4_mb_generate_buddy:745: group 1122, block bitmap and bg descriptor inconsistent: 8192 vs 8197 free clusters
[    4.143272] EXT4-fs error (device mmcblk2p2): ext4_validate_block_bitmap:387: comm systemd: bg 1793: bad block bitmap checksum
[    7.115195] EXT4-fs error (device mmcblk2p2): ext4_mb_generate_buddy:745: group 1153, block bitmap and bg descriptor inconsistent: 480 vs 481 free clusters
[   20.976118] EXT4-fs error (device mmcblk2p2): ext4_validate_block_bitmap:387: comm kworker/u8:2: bg 1442: bad block bitmap checksum

**Comment by SolidHal** [comment]
Would be interesting to run fsck on /dev/mmcblk2p2 when booted from usb or sd card and see if these get fixed. I recall having issues getting fsck to run on reboot properly.

**Comment by Anthony-Sensors** [comment]
Yes this fixed the issue.

**Comment by SolidHal** [comment]
Sorry, I should have clarified-- as far as I know most linux distros will run fsck on reboot once and a while. I don't believe PrawnOS is doing that properly. I'm not totally sure how to approach it as setting the "run fsck on reboot" flag doesn't seem to work, and I think thats how distros implement the fsck on reboot. I'll have to see if it's something in the kernel. 

For now, all I can suggest is to avoid force shutting off the machine, and running fsck on /dev/mmcblk2p2 when booted from usb or sd if you do have to force shut it off. 

I'm keeping this open to make sure I look into this.

**Comment by Anthony-Sensors** [comment]
I had to force restart the computer as I experienced a freeze while letting the computer sit idle for the whole night.

**Comment by SolidHal** [comment]
seems that maybe we should be passing "ro" instead of "rw" to the kernel cmdline so that the kernel can run fsck if need be and then mount it as rw?
Additionally, these parameters can be passed to force a fsck:

http://www.freedesktop.org/software/systemd/man/systemd-fsck@.service.html

**Comment by SolidHal** [comment]
looks like PrawnOs wasn't using a journaled filesystem after all due to `^has_journal` in the install to internal script and the build filesystem script. I have removed them and will be testing to ensure nothing strange occurs. 

So, that is likely why we have seen EXT4 errors-- because we weren't even trying to prevent them.

**Comment by SolidHal** [comment]
commit 7ad3f7462b0097439182a7c36998c7162d5540eb contains the fixes to fstab and filesystem creation and seems to fix any issues seen. 

the proper fstab and cmdline also fixed the issue of not being able to run fsck on boot. Now you can run `touch /forcefsck` and fsck will be run on the next reboot.

**Comment by SolidHal** [comment]
closing this, as filesystem stability seems to be fixed!
