### ISSUE TITLE
Add a debian buster based release.

### ISSUE THREAD

**Issue by Anthony-Sensors** [SolidHal/PrawnOS#87]
The full-freeze is schedule for 12 of march. 
Should /etc/apt/preferences and /etc/apt/sources.list be changed to buster?
"deb http://deb.debian.org/debian/ buster main"

**Comment by SolidHal** [comment]
I would like to do a proper stable release on stretch before migrating to buster. Since the freeze is still recent, and no full buster release has happened I think we can hold off on this for now. I'll make an issue listing the things I would like to achieve for a "stable" release.

**Comment by JeremyRand** [comment]
@Anthony-Sensors could you try testing https://github.com/SolidHal/PrawnOS/pull/96 ?  Would be good to get feedback on it.

**Comment by SolidHal** [comment]
> I would like to do a proper stable release on stretch before migrating to buster. Since the freeze is still recent, and no full buster release has happened I think we can hold off on this for now. I'll make an issue listing the things I would like to achieve for a "stable" release.

I have since rethought my stance on this, in testing buster seems quite stable. Since we already get a couple packages from buster, much of the encryption testing has been on buster, and more packages are available in general on buster switching to buster makes sense to me.

**Comment by SolidHal** [comment]
With release 10, buster is now used instead of stretch. Closing.
