### ISSUE TITLE
InstallToInternal script doesn't target sd cards properly

### ISSUE THREAD

**Issue by MagicFab** [SolidHal/PrawnOS#90]
I have a system with the "other" smaller EMMC type. I am not sure if this is specific to my system because of this.

I flashed a microSD card and booted from it, then expanded the storage as per the README.

When executing the InstallToInternal.sh script it refers to /dev/sd* devices but they don't exist.

When booting from microSD the device is /dev/mmcblk0. Replacing /dev/sd* in both dd commands in the script by the corresponding /dev/mmcblk0/p* worked for me.

**Comment by SolidHal** [comment]
This isnt due to the type of emmc, rather that the sd card is mapped to /dev/mmcblk0 while usb drives are mapped to /dev/sd*

I've been meaning to fix the scripts to actually support installing from sd cards/
