### ISSUE TITLE
Is Chromium supposed to come from Buster or Sid?

### ISSUE THREAD

**Issue by JeremyRand** [SolidHal/PrawnOS#97]
The PrawnOS repo is inconsistent on whether Chromium is supposed to be installed from Buster or Sid.

It says Sid here:

https://github.com/SolidHal/PrawnOS/blob/cf4d9f8327cd7f35d8eda6b58446fbad30b68ef8/resources/BuildResources/sources.list#L16

https://github.com/SolidHal/PrawnOS/blob/9c71414f5bb2effd1c44e77f955085632648c70d/scripts/InstallScripts/InstallPackages.sh#L40

But it says Buster here:

https://github.com/SolidHal/PrawnOS/blob/9c71414f5bb2effd1c44e77f955085632648c70d/scripts/buildFilesystem.sh#L147

Can this inconsistency be fixed?

**Comment by SolidHal** [comment]
It used to be from sid, but sid is broken and buster works again. I'll change the comments to be accurate.
